#if !defined INCLUDED__ESP32_SMART_BEENS_V0__ENERGY_OPTIMIZATION_HPP
#define INCLUDED__ESP32_SMART_BEENS_V0__ENERGY_OPTIMIZATION_HPP


// void print_wakeup_reason();



#endif /* INCLUDED__ESP32_SMART_BEENS_V0__ENERGY_OPTIMIZATION_HPP */