#if !defined INCLUDED__ESP32_SMART_BEENS_V0__SECRETS_H
#define INCLUDED__ESP32_SMART_BEENS_V0__SECRETS_H


/* LTE MODEM */
#define THINGSPEAK_WRITE_API_KEY    ""


#endif /* INCLUDED__ESP32_SMART_BEENS_V0__SECRETS_H */